#basic net core build recipe

steps:
- task: DotNetCoreInstaller@0
  displayName: Install DotNet
  inputs:
    version: '2.1.300'

- script: dotnet restore

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Debug'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: '**/ConcurrentPriorityQueue/*.csproj'
    packDirectory: 
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'

- task: NuGetCommand@2
  displayName: Push
  inputs:
    command: 'push'
    packagesToPush: '/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget'

